# permissions for end users to view mongodbreplicasets.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: mongodbreplicaset-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: mongodb-operator
    app.kubernetes.io/part-of: mongodb-operator
    app.kubernetes.io/managed-by: kustomize
  name: mongodbreplicaset-viewer-role
rules:
- apiGroups:
  - mongodb.example.com
  resources:
  - mongodbreplicasets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - mongodb.example.com
  resources:
  - mongodbreplicasets/status
  verbs:
  - get
