# permissions for end users to edit mongodbreplicasets.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: mongodbreplicaset-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: mongodb-operator
    app.kubernetes.io/part-of: mongodb-operator
    app.kubernetes.io/managed-by: kustomize
  name: mongodbreplicaset-editor-role
rules:
- apiGroups:
  - mongodb.example.com
  resources:
  - mongodbreplicasets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - mongodb.example.com
  resources:
  - mongodbreplicasets/status
  verbs:
  - get
